### ISSUE TITLE
[질문] li image

### ISSUE THREAD

**Issue by byunjiin** [sprint-part1-team13/project4#3]
list-style-image로 해당 이미지를 넣으면 gap도 줄 수 없고, 높이도 정렬해 줄 수 없는데 어떻게 하셨나요?

>>저는 이렇게 풀었는데 다른분들 풀이가 궁금합니다.
li{
  display: flex;
  gap: 16px;
}
li::before{ 
  content: url(../assets/images/icon-list.svg);
}

**Comment by kimtaejin3** [comment]
```css
.main-list-item {
  padding-left: 36px;
  /* text-indent: -20px; */
}

.main-list-item::before {
  content: "";
  width: 21px;
  height: 21px;
  background-image: url(./assets/images/icon-list.svg);
  display: inline-block;
  margin-left: -36px;
  margin-right: 15px;
  margin-bottom: -5px;
}
```
.main-list-item이 li입니다
저는 이렇게 했습니다!
